---
name: Ansible Role Molecule Test
on:
  workflow_call:
    inputs:
      role-name:
        required: true
        type: string
      branch-name:
        required: false
        default: "main"
        type: string
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Test with molecule
        uses: robertdebock/molecule-action@5.0.3
        with:
          namespace: "robertdebock"
          command: lint
  molecule-check-debian:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        tag:
          - "bullseye"
          - "bookworm"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Test with molecule
        uses: robertdebock/molecule-action@5.0.3
        with:
          namespace: "robertdebock"
          image: "debian"
          tag: "${{ matrix.tag }}"
          command: test
