---
name: Ansible Role Molecule Test
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
jobs:
  molecule-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Test with molecule
        uses: robertdebock/molecule-action@5.0.2
        with:
          image: ${{ inputs.image }}
          tag: ${{ inputs.tag }}
