---
name: Ansible Role Molecule Test
on:
  workflow_call:
    inputs:
      role-name:
        required: true
        type: string
      branch-name:
        required: false
        default: "main"
        type: string
jobs:
  molecule-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # python-version:
        #   - "3.9"
        #   - "3.10"
        #   - "3.11"
        distro:
          - "centos8"
          - "rockylinux9"
          - "debian10"
          - "debian11"
          - "debian12"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Test with molecule
        uses: robertdebock/molecule-action@5.0.3
        with:
          image: "${{ matrix.distro }}"
          options: parallel
          command: test
