---
name: Ansible Role Molecule Test
on:
  workflow_call:
    inputs:
      role-name:
        required: true
        type: string
      branch-name:
        required: false
        default: "main"
        type: string
jobs:
  molecule-check:
    runs-on: ubuntu-latest
    # runs-on: robertdebock/docker-github-action-molecule:latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        distro:
          - "centos8"
          - "rockylinux9"
          - "debian10"
          - "debian11"
          - "debian12"
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ inputs.role-name }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          apt install docker
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible molecule[docker] docker
      - name: Test with molecule
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        working-directory: ${{ inputs.role-name }}
        run: molecule test
