---
name: Ansible Role Molecule Test
on:
  workflow_call:
    inputs:
      role-name:
        required: true
        type: string
      branch-name:
        required: false
        default: "main"
        type: string
jobs:
  molecule-check-debian:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        tag:
          - "bullseye"
          - "bookworm"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Test with molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          namespace: "robertdebock"
          image: "debian"
          tag: "${{ matrix.tag }}"
          command: test
