---
name: Ansible Role Release
on:
  workflow_call:
    inputs:
      git-branch:
        required: false
        default: "main"
        type: string
    secrets:
      GALAXY_API_KEY:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: ${{ inputs.git-branch }}
# jobs:
#   build:
#     name: Galaxy Role Importer
#     runs-on: ubuntu-latest

#     steps:
#       - name: 'Checkout git repo'
#         uses: actions/checkout@v4
#         with:
#           submodules: true
#           fetch-depth: 0

#       - name: 'Release on galaxy'
#         uses: ansible-actions/ansible-galaxy-action@v1.2.0
#         with:
#           galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
