---
name: Ansible Role Molecule Test
on:
  workflow_call:
    inputs:
      role-name:
        required: true
        type: string
      branch-name:
        required: false
        default: "main"
        type: string
jobs:
  molecule-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        distro:
          - "debian"
        release:
          - "bullseye"
          - "bookworm"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Test with molecule
        uses: robertdebock/molecule-action@5.0.3
        with:
          namespace: "robertdebock"
          image: "${{ matrix.distro }}"
          tag: "${{ matrix.release }}"
          options: parallel
          command: test
